---

- hosts: all
  become: true
  pre_tasks:

    - name: System Update
      tags: always
      apt:
        upgrade: dist
        update_cache: yes


- hosts: all
  become: true
  tasks:

    - name: Install Cinder
      apt:
        name:
          - cinder-api
        state: latest

    - name: Install Horizon
      apt:
        name:
          - openstack-dashboard
        state: latest

    - name: Install neutron-server
      apt:
        name:
          - neutron-server
        state: latest
